### ISSUE TITLE
User is able to scroll part of the webpage off of the screen

### ISSUE THREAD

**Issue by Agunderman10** [0xaryan/0xaryan.github.io#2]
The user is able to horizontally scroll half of the webpage off of the screen if they so choose by simply using the scroll bar to scroll to the right.

**Comment by avestura** [comment]
Thanks for the report Andrew

Can you please give me more details that when this happens? Because "this does not happen on my machine" 😁
Does this happen on every browser?
Also can you attach an screenshot?

**Comment by Agunderman10** [comment]
![screenshot 4](https://user-images.githubusercontent.com/28486005/50407524-c1dd9280-07a6-11e9-9f72-3e4e9890acca.png)

This does not seem to happen on Google Chrome, but I have not been able to test it on any other browsers. I was on Edge when this happens. The user has the option to scroll horizontally which allows the user to scroll part of the site off of the screen as demonstrated in this screenshot. This also cuts off part of the navigation bar.
